# This is a sample build configuration for Python.
# You can specify a custom docker image from Docker Hub as your build environment.
image: python:2.7.12

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - pip install -U tox
          - pip --version
          - tox --version