# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 14:48
from __future__ import unicode_literals

from django.db import migrations
from django.apps import apps

Degree = apps.get_model("talent_portal", "degree")
Course = apps.get_model("talent_portal", "course")
SUPERADMIN_EMAIL_ADDRESS = "admin@abc.com"  # FIXME: change to real email address later

def forward_func(*args, **kwargs):
    print("Inserting Domains and Courses in database...")

    try:
        Degree.objects.create(name="Any U.G.", alias=None, created_by=SUPERADMIN_EMAIL_ADDRESS)
        Degree.objects.create(name="Any Engineering", alias=None,
                              created_by=SUPERADMIN_EMAIL_ADDRESS)
        Degree.objects.create(name="Any Management", alias=None,
                              created_by=SUPERADMIN_EMAIL_ADDRESS)
        Degree.objects.create(name="Any Computers", alias=None,
                              created_by=SUPERADMIN_EMAIL_ADDRESS)
        Degree.objects.create(name="Any Hotel Management", alias=None,
                              created_by=SUPERADMIN_EMAIL_ADDRESS)
        Degree.objects.create(name="Any Diploma Holders", alias=None,
                              created_by=SUPERADMIN_EMAIL_ADDRESS)
        Degree.objects.create(name="Any Medical", alias=None,
                              created_by=SUPERADMIN_EMAIL_ADDRESS)

        Degree.objects.create(name="Bachelor of Arts", alias="BA",
                              created_by=SUPERADMIN_EMAIL_ADDRESS)
        Course.objects.create(name="All", alias=None, created_by=SUPERADMIN_EMAIL_ADDRESS)
        Course.objects.create(name="Arts & Humanities", alias=None,
                              created_by=SUPERADMIN_EMAIL_ADDRESS)
        Course.objects.create(name="Communication", alias=None,
                              created_by=SUPERADMIN_EMAIL_ADDRESS)
        Course.objects.create(name="Economics", alias=None, created_by=SUPERADMIN_EMAIL_ADDRESS)
        Course.objects.create(name="English", alias=None, created_by=SUPERADMIN_EMAIL_ADDRESS)
        Course.objects.create(name="Film", alias=None, created_by=SUPERADMIN_EMAIL_ADDRESS)
        Course.objects.create(name="Fine Arts", alias=None, created_by=SUPERADMIN_EMAIL_ADDRESS)
        Course.objects.create(name="Hindi", alias=None, created_by=SUPERADMIN_EMAIL_ADDRESS)
        Course.objects.create(name="History", alias=None, created_by=SUPERADMIN_EMAIL_ADDRESS)
        Course.objects.create(name="Journalism", alias=None,
                              created_by=SUPERADMIN_EMAIL_ADDRESS)
        Course.objects.create(name="Maths", alias=None, created_by=SUPERADMIN_EMAIL_ADDRESS)
        Course.objects.create(name="Pass Course", alias=None,
                              created_by=SUPERADMIN_EMAIL_ADDRESS)
        Course.objects.create(name="Political Science", alias=None,
                              created_by=SUPERADMIN_EMAIL_ADDRESS)
        Course.objects.create(name="PR/Advertising", alias=None,
                              created_by=SUPERADMIN_EMAIL_ADDRESS)
        Course.objects.create(name="Psychology", alias=None,
                              created_by=SUPERADMIN_EMAIL_ADDRESS)
        Course.objects.create(name="Sanskrit", alias=None, created_by=SUPERADMIN_EMAIL_ADDRESS)
        Course.objects.create(name="Sociology", alias=None, created_by=SUPERADMIN_EMAIL_ADDRESS)
        Course.objects.create(name="Statistics", alias=None,
                              created_by=SUPERADMIN_EMAIL_ADDRESS)
        Course.objects.create(name="Vocational Course", alias=None,
                              created_by=SUPERADMIN_EMAIL_ADDRESS)
        Course.objects.create(name="Others", alias=None, created_by=SUPERADMIN_EMAIL_ADDRESS)

        Degree.objects.create(name="Bachelor of Architecture", alias="B.Arch",
                              created_by=SUPERADMIN_EMAIL_ADDRESS)
        Degree.objects.create(name="Bachelor of Computer Application", alias="BCA",
                              created_by=SUPERADMIN_EMAIL_ADDRESS)
        Degree.objects.create(name="Bachelor of Business Administration", alias="BBA",
                              created_by=SUPERADMIN_EMAIL_ADDRESS)
        Degree.objects.create(name="Bachelor of Commerce", alias="B.Com",
                              created_by=SUPERADMIN_EMAIL_ADDRESS)
        Degree.objects.create(name="Bachelor of Education", alias="B.Ed",
                              created_by=SUPERADMIN_EMAIL_ADDRESS)
        Degree.objects.create(name="Bachelor of Dental Science", alias="BDS",
                              created_by=SUPERADMIN_EMAIL_ADDRESS)
        Degree.objects.create(name="Bachelor of Hotel Management", alias="BHM",
                              created_by=SUPERADMIN_EMAIL_ADDRESS)
        Degree.objects.create(name="Bachelor of Pharmacy", alias="B.Pharma",
                              created_by=SUPERADMIN_EMAIL_ADDRESS)

        Degree.objects.create(name="Bachelor of Science", alias="B.Sc",
                              created_by=SUPERADMIN_EMAIL_ADDRESS)
        Course.objects.create(name="All", alias=None, created_by=SUPERADMIN_EMAIL_ADDRESS)
        Course.objects.create(name="Agriculture", alias=None,
                              created_by=SUPERADMIN_EMAIL_ADDRESS)
        Course.objects.create(name="Anthropology", alias=None,
                              created_by=SUPERADMIN_EMAIL_ADDRESS)
        Course.objects.create(name="Bio Chemistry", alias=None,
                              created_by=SUPERADMIN_EMAIL_ADDRESS)
        Course.objects.create(name="Botany", alias=None, created_by=SUPERADMIN_EMAIL_ADDRESS)
        Course.objects.create(name="Chemistry", alias=None, created_by=SUPERADMIN_EMAIL_ADDRESS)
        Course.objects.create(name="Computer", alias=None, created_by=SUPERADMIN_EMAIL_ADDRESS)
        Course.objects.create(name="Dairy Technology", alias=None,
                              created_by=SUPERADMIN_EMAIL_ADDRESS)
        Course.objects.create(name="Electronics", alias=None,
                              created_by=SUPERADMIN_EMAIL_ADDRESS)
        Course.objects.create(name="Environmental", alias=None,
                              created_by=SUPERADMIN_EMAIL_ADDRESS)
        Course.objects.create(name="Food Technology", alias=None,
                              created_by=SUPERADMIN_EMAIL_ADDRESS)
        Course.objects.create(name="Geology", alias=None, created_by=SUPERADMIN_EMAIL_ADDRESS)
        Course.objects.create(name="Home Science", alias=None,
                              created_by=SUPERADMIN_EMAIL_ADDRESS)
        Course.objects.create(name="Maths", alias=None, created_by=SUPERADMIN_EMAIL_ADDRESS)
        Course.objects.create(name="Microbiology", alias=None,
                              created_by=SUPERADMIN_EMAIL_ADDRESS)
        Course.objects.create(name="Nursing", alias=None, created_by=SUPERADMIN_EMAIL_ADDRESS)
        Course.objects.create(name="Physics", alias=None, created_by=SUPERADMIN_EMAIL_ADDRESS)
        Course.objects.create(name="Statistics", alias=None,
                              created_by=SUPERADMIN_EMAIL_ADDRESS)
        Course.objects.create(name="Zoology", alias=None, created_by=SUPERADMIN_EMAIL_ADDRESS)
        Course.objects.create(name="General", alias=None, created_by=SUPERADMIN_EMAIL_ADDRESS)
        Course.objects.create(name="Others", alias=None, created_by=SUPERADMIN_EMAIL_ADDRESS)

        Degree.objects.create(name="Bachelor of Technology", alias="B.Tech/BE",
                              created_by=SUPERADMIN_EMAIL_ADDRESS)
        Course.objects.create(name="All", alias=None, created_by=SUPERADMIN_EMAIL_ADDRESS)
        Course.objects.create(name="Agriculture", alias=None,
                              created_by=SUPERADMIN_EMAIL_ADDRESS)
        Course.objects.create(name="Automation", alias=None,
                              created_by=SUPERADMIN_EMAIL_ADDRESS)
        Course.objects.create(name="Aviation", alias=None, created_by=SUPERADMIN_EMAIL_ADDRESS)
        Course.objects.create(name="Bio Chemistry", alias=None,
                              created_by=SUPERADMIN_EMAIL_ADDRESS)
        Course.objects.create(name="Bio Technology", alias=None,
                              created_by=SUPERADMIN_EMAIL_ADDRESS)
        Course.objects.create(name="Bio Medical", alias=None,
                              created_by=SUPERADMIN_EMAIL_ADDRESS)
        Course.objects.create(name="Ceramics", alias=None, created_by=SUPERADMIN_EMAIL_ADDRESS)
        Course.objects.create(name="Chemical", alias=None, created_by=SUPERADMIN_EMAIL_ADDRESS)
        Course.objects.create(name="Civil", alias=None, created_by=SUPERADMIN_EMAIL_ADDRESS)
        Course.objects.create(name="Computers", alias=None, created_by=SUPERADMIN_EMAIL_ADDRESS)
        Course.objects.create(name="Electrical", alias=None,
                              created_by=SUPERADMIN_EMAIL_ADDRESS)
        Course.objects.create(name="Electronics and Communication", alias=None,
                              created_by=SUPERADMIN_EMAIL_ADDRESS)
        Course.objects.create(name="Energy", alias=None, created_by=SUPERADMIN_EMAIL_ADDRESS)
        Course.objects.create(name="Environmental", alias=None,
                              created_by=SUPERADMIN_EMAIL_ADDRESS)
        Course.objects.create(name="Instrumentation", alias=None,
                              created_by=SUPERADMIN_EMAIL_ADDRESS)
        Course.objects.create(name="Marine", alias=None, created_by=SUPERADMIN_EMAIL_ADDRESS)
        Course.objects.create(name="Mechanical", alias=None,
                              created_by=SUPERADMIN_EMAIL_ADDRESS)
        Course.objects.create(name="Metallurgy", alias=None,
                              created_by=SUPERADMIN_EMAIL_ADDRESS)
        Course.objects.create(name="Mineral", alias=None, created_by=SUPERADMIN_EMAIL_ADDRESS)
        Course.objects.create(name="Mining", alias=None, created_by=SUPERADMIN_EMAIL_ADDRESS)
        Course.objects.create(name="Nuclear", alias=None, created_by=SUPERADMIN_EMAIL_ADDRESS)
        Course.objects.create(name="Paint/Oil", alias=None, created_by=SUPERADMIN_EMAIL_ADDRESS)
        Course.objects.create(name="Petroleum", alias=None, created_by=SUPERADMIN_EMAIL_ADDRESS)
        Course.objects.create(name="Plastics", alias=None, created_by=SUPERADMIN_EMAIL_ADDRESS)
        Course.objects.create(name="Industrial Production", alias=None,
                              created_by=SUPERADMIN_EMAIL_ADDRESS)
        Course.objects.create(name="Textile", alias=None, created_by=SUPERADMIN_EMAIL_ADDRESS)
        Course.objects.create(name="Other", alias=None, created_by=SUPERADMIN_EMAIL_ADDRESS)

        Degree.objects.create(name="Bachelor of Laws", alias="LLB",
                              created_by=SUPERADMIN_EMAIL_ADDRESS)

        Degree.objects.create(name="Diploma", alias=None, created_by=SUPERADMIN_EMAIL_ADDRESS)
        Course.objects.create(name="All", alias=None, created_by=SUPERADMIN_EMAIL_ADDRESS)
        Course.objects.create(name="Architecture", alias=None,
                              created_by=SUPERADMIN_EMAIL_ADDRESS)
        Course.objects.create(name="Chemical", alias=None, created_by=SUPERADMIN_EMAIL_ADDRESS)
        Course.objects.create(name="Civil", alias=None, created_by=SUPERADMIN_EMAIL_ADDRESS)
        Course.objects.create(name="Computers", alias=None, created_by=SUPERADMIN_EMAIL_ADDRESS)
        Course.objects.create(name="Electrical", alias=None,
                              created_by=SUPERADMIN_EMAIL_ADDRESS)
        Course.objects.create(name="Electronics & Telecommunication", alias=None,
                              created_by=SUPERADMIN_EMAIL_ADDRESS)
        Course.objects.create(name="Engineering", alias=None,
                              created_by=SUPERADMIN_EMAIL_ADDRESS)
        Course.objects.create(name="Export/Import", alias=None,
                              created_by=SUPERADMIN_EMAIL_ADDRESS)
        Course.objects.create(name="Fashion Designing", alias=None,
                              created_by=SUPERADMIN_EMAIL_ADDRESS)
        Course.objects.create(name="Graphic/Web Designing", alias=None,
                              created_by=SUPERADMIN_EMAIL_ADDRESS)
        Course.objects.create(name="Hotel Management", alias=None,
                              created_by=SUPERADMIN_EMAIL_ADDRESS)
        Course.objects.create(name="Insurance", alias=None, created_by=SUPERADMIN_EMAIL_ADDRESS)
        Course.objects.create(name="Management", alias=None,
                              created_by=SUPERADMIN_EMAIL_ADDRESS)
        Course.objects.create(name="Tourism", alias=None, created_by=SUPERADMIN_EMAIL_ADDRESS)
        Course.objects.create(name="Visual Art", alias=None,
                              created_by=SUPERADMIN_EMAIL_ADDRESS)
        Course.objects.create(name="Vocational", alias=None,
                              created_by=SUPERADMIN_EMAIL_ADDRESS)
        Course.objects.create(name="Others", alias=None, created_by=SUPERADMIN_EMAIL_ADDRESS)

        Degree.objects.create(name="Bachelor of Veternary Sc", alias=None,
                              created_by=SUPERADMIN_EMAIL_ADDRESS)
        Degree.objects.create(name="Fashion Designing", alias=None,
                              created_by=SUPERADMIN_EMAIL_ADDRESS)
        Degree.objects.create(name="Mass Communication/Journalism", alias=None,
                              created_by=SUPERADMIN_EMAIL_ADDRESS)
        Degree.objects.create(name="PR/Advertising", alias=None,
                              created_by=SUPERADMIN_EMAIL_ADDRESS)
        Degree.objects.create(name="Tourism", alias=None, created_by=SUPERADMIN_EMAIL_ADDRESS)
        Degree.objects.create(name="Vocational Training", alias=None,
                              created_by=SUPERADMIN_EMAIL_ADDRESS)
        Degree.objects.create(name="Others", alias=None, created_by=SUPERADMIN_EMAIL_ADDRESS)

        Degree.objects.create(name="Chartered Accountant", alias="CA",
                              created_by=SUPERADMIN_EMAIL_ADDRESS)
        Degree.objects.create(name="Company Secretary", alias="CS",
                              created_by=SUPERADMIN_EMAIL_ADDRESS)
        Degree.objects.create(name="Indian Child Welfare Act", alias="ICWA",
                              created_by=SUPERADMIN_EMAIL_ADDRESS)
        Degree.objects.create(name="Integrated PG course", alias=None,
                              created_by=SUPERADMIN_EMAIL_ADDRESS)
        Degree.objects.create(name="Journalism/Mass Communication", alias=None,
                              created_by=SUPERADMIN_EMAIL_ADDRESS)
        Degree.objects.create(name="LLM", alias=None, created_by=SUPERADMIN_EMAIL_ADDRESS)
        Degree.objects.create(name="MA", alias=None, created_by=SUPERADMIN_EMAIL_ADDRESS)

        Degree.objects.create(name="Masters of Architecture", alias="M.Arch",
                              created_by=SUPERADMIN_EMAIL_ADDRESS)
        Degree.objects.create(name="Masters of Commerce", alias="M.Com",
                              created_by=SUPERADMIN_EMAIL_ADDRESS)
        Degree.objects.create(name="Masters of Pharmacy", alias="M.Pharma",
                              created_by=SUPERADMIN_EMAIL_ADDRESS)
        Degree.objects.create(name="Masters of Sciences", alias="M.Sc",
                              created_by=SUPERADMIN_EMAIL_ADDRESS)

        Degree.objects.create(name="Masters of Technology", alias="B.Tech/BE",
                              created_by=SUPERADMIN_EMAIL_ADDRESS)
        Degree.objects.create(name="Masters of Business Administration", alias="MBA",
                              created_by=SUPERADMIN_EMAIL_ADDRESS)

        Course.objects.create(name="Advertising/ Mass Com", alias=None,
                              created_by=SUPERADMIN_EMAIL_ADDRESS)
        Course.objects.create(name="Finance", alias=None, created_by=SUPERADMIN_EMAIL_ADDRESS)
        Course.objects.create(name="HR", alias=None, created_by=SUPERADMIN_EMAIL_ADDRESS)
        Course.objects.create(name="IT", alias=None, created_by=SUPERADMIN_EMAIL_ADDRESS)
        Course.objects.create(name="International Business", alias=None,
                              created_by=SUPERADMIN_EMAIL_ADDRESS)
        Course.objects.create(name="Marketing", alias=None, created_by=SUPERADMIN_EMAIL_ADDRESS)
        Course.objects.create(name="Systems", alias=None, created_by=SUPERADMIN_EMAIL_ADDRESS)

        Degree.objects.create(name="Masters of Computer Application", alias="MCA",
                              created_by=SUPERADMIN_EMAIL_ADDRESS)
        Degree.objects.create(name="Medical (MS/MD)", alias=None,
                              created_by=SUPERADMIN_EMAIL_ADDRESS)
        Degree.objects.create(name="M.V.Sc", alias=None, created_by=SUPERADMIN_EMAIL_ADDRESS)
        Degree.objects.create(name="PG Diploma", alias=None,
                              created_by=SUPERADMIN_EMAIL_ADDRESS)
        Degree.objects.create(name="Tourism", alias=None, created_by=SUPERADMIN_EMAIL_ADDRESS)
        Degree.objects.create(name="Others", alias=None, created_by=SUPERADMIN_EMAIL_ADDRESS)
    except Exception as e:
        print("There was some error: " + str(e))

    print ("Insertion complete!")


def reverse_func(*args, **kwargs):
    print("Removing all data from Domains and Courses")
    try:
        Degree.objects.all().delete()
        Course.objects.all().delete()
    except Exception as e:
        print("There was some error: " + str(e))

    print("Removed all data from Degrees and Courses")


class Migration(migrations.Migration):
    dependencies = [
        ('talent_portal', '0003_CompanyCourseSkillIndustryFuncArea_tables_added'),
    ]

    operations = [
        migrations.RunPython(forward_func, reverse_code=reverse_func),
    ]
