# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-06 19:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent_portal', '0010_more_fields_added_to_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='dob',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
