# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-02 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent_portal', '0012_job_jobapplicant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
