# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-10 00:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent_portal', '0013_MobileMadeNullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='resume_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
